version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php 
    ports:
      - "8080:80"